### PR TITLE
More updates with best current knowledge

### PR DESCRIPTION
**Pull request by kanavin**
I've also added an example of how to write interfaces, their implementations, virtual methods, properties and signals (copied and tweaked from GObject manual).

### CODE REVIEW

**Comment by acrisci** [comment]
Good work. This is why I made this project, to learn cool stuff like this :+1: .

Please update the readme with an example of the features you have added.

**Comment by kanavin** [comment]
hey, are the new commits in this pull request ok?

**Comment by acrisci** [comment]
Yeah I'm just waiting until I have time to really go through it properly.

**Comment by acrisci** [comment]
Sorry for taking forever on this. It kind of slipped my mind for awhile. Anyway, it looks good :+1:.

**Pull request merged**
